In [1]:
import pandas as pd

In [2]:
# Confirm the current working directory and check that the expected files are here
import os

print(os.getcwd())
print(os.listdir())

/sessions/rcw-01btrx2z8p2amqzpvumuzrrz/mnt/DataMS1
['MotorPH_Preprocessing.py', 'MotorPH_Product_Analysis.ipynb', '.DS_Store', 'MotorPH_Preprocessing.ipynb', 'MotorPH_Products_List_2025.csv', 'MotorPH_Product_Analysis.py', 'MotorPH_Sales_2025_Cleaned.csv', 'MotorPH_Sales Data-3rd Quarter-Year 2025.csv', '.ipynb_checkpoints', '.claude_build_tmp', 'MotorPH_Products_List_2025_Cleaned.csv']

In [3]:
# Load the raw Product List and raw Sales datasets
products = pd.read_csv("MotorPH_Products_List_2025.csv")

sales = pd.read_csv("MotorPH_Sales Data-3rd Quarter-Year 2025.csv")

In [4]:
# Preview the first few rows of the Product List dataset
products.head()

   EntrNo                   EntrName  ... Acquisiton  UnitPrice
0       1              Honda CBR500R  ...       2023     389000
1       2               Yamaha MT-15  ...       2023     178000
2       3         Kawasaki Ninja 400  ...       2024     340000
3       4      Suzuki Raider R150 Fi  ...       2021     119900
4       5  Royal Enfield Classic 350  ...       2023     250000

[5 rows x 6 columns]

In [5]:
# Preview the first few rows of the Sales dataset
sales.head()

        date client_type               product  ...  quantity     total      payment
0  7/22/2025      Retail          Zontes GK350  ...        20   5380000         Cash
1  6/15/2025   Wholesale        Yamaha FZi 150  ...        18   1798200  Credit card
2  8/11/2025   Wholesale          Zontes GK350  ...        41  11029000  Credit card
3  7/31/2025      Retail  Italjet Dragster 200  ...        50  14450000         Cash
4  6/21/2025   Wholesale           Zontes 310X  ...         7   1736000         Cash

[5 rows x 7 columns]

In [6]:
# Check column names, data types, and non-null counts for the Product List
print("=== PRODUCT LIST INFORMATION ===")
products.info()

=== PRODUCT LIST INFORMATION ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EntrNo              50 non-null     int64
 1   EntrName            50 non-null     object
 2   EntrDetails         50 non-null     object
 3   Manufacturing Date  50 non-null     int64
 4   Acquisiton          50 non-null     int64
 5   UnitPrice           50 non-null     int64
dtypes: int64(4), object(2)
memory usage: 2.5+ KB

In [7]:
# Check column names, data types, and non-null counts for the Sales dataset
print("=== SALES DATASET INFORMATION ===")
sales.info()

=== SALES DATASET INFORMATION ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         998 non-null    object
 1   client_type  990 non-null    object
 2   product      1000 non-null   object
 3   unitprice    1000 non-null   int64
 4   quantity     1000 non-null   int64
 5   total        1000 non-null   int64
 6   payment      990 non-null    object
dtypes: int64(3), object(4)
memory usage: 54.8+ KB

In [8]:
# Check both datasets for missing values
print("=== PRODUCT LIST MISSING VALUES ===")
print(products.isnull().sum())

print("\n=== SALES DATASET MISSING VALUES ===")
print(sales.isnull().sum())

=== PRODUCT LIST MISSING VALUES ===
EntrNo                0
EntrName              0
EntrDetails           0
Manufacturing Date    0
Acquisiton            0
UnitPrice             0
dtype: int64

=== SALES DATASET MISSING VALUES ===
date            2
client_type    10
product         0
unitprice       0
quantity        0
total           0
payment        10
dtype: int64

In [9]:
# Check both datasets for fully duplicated rows
print("=== PRODUCT LIST DUPLICATES ===")
print("Duplicate rows:", products.duplicated().sum())

print("\n=== SALES DATASET DUPLICATES ===")
print("Duplicate rows:", sales.duplicated().sum())

=== PRODUCT LIST DUPLICATES ===
Duplicate rows: 0

=== SALES DATASET DUPLICATES ===
Duplicate rows: 0

In [10]:
# Confirm every product has a unique EntrNo, and list all product IDs
print("Duplicate Product IDs:", products["EntrNo"].duplicated().sum())
print("Product IDs:")
print(products["EntrNo"].tolist())

Duplicate Product IDs: 0
Product IDs:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

In [11]:
# Review product names, and the categorical values in the Sales dataset
print("=== PRODUCT NAMES ===")
print(products["EntrName"].tolist())

print("\n=== SALES CLIENT TYPES ===")
print(sales["client_type"].value_counts(dropna=False))

print("\n=== SALES PAYMENT TYPES ===")
print(sales["payment"].value_counts(dropna=False))

=== PRODUCT NAMES ===
['Honda CBR500R', 'Yamaha MT-15', 'Kawasaki Ninja 400', 'Suzuki Raider R150 Fi', 'Royal Enfield Classic 350', 'CFMoto 300NK', 'Bristol Veloce 500', 'KTM Duke 200', 'Yamaha XSR155', 'Bajaj Dominar 400', 'Yamaha NMAX 155', 'Honda ADV 160', 'Suzuki Avenis 125', 'KTM RC 200', 'BMW G 310 GS', 'TVS Apache RTR 200 4V', 'Husqvarna Svartpilen 401', 'Vespa Primavera 150', 'Suzuki GSX-S150', 'Kawasaki Z400', 'Yamaha Aerox 155', 'Bristol Bobber 650', 'Keeway RKS 150 Sport', 'Motorstar Xplorer 250R', 'CFMoto 650MT', 'Honda Click 125i', 'Yamaha Sniper 155', 'Bajaj CT125', 'Honda CRF300L', 'Rusi Flash 125', 'SYM Jet X 150', 'Harley-Davidson Street 750', 'Zontes 310X', 'Aprilia SR GT 200', 'Yamaha XMAX 300', 'Benelli 502C', 'Moto Morini X-Cape 650', 'Yamaha FZi 150', 'Vespa GTS Super 300', 'Kawasaki KLX 230', 'BMW R nineT', 'Honda Rebel 1100', 'KTM 790 Duke', 'CFMoto 300SR', 'Italjet Dragster 200', 'Yamaha Serow 250', 'Suzuki Burgman Street 125', 'Zontes GK350', 'Moto Guzzi V7 Stone', 'SYM Husky 150']

=== SALES CLIENT TYPES ===
client_type
Retail       521
Wholesale    469
NaN           10
Name: count, dtype: int64

=== SALES PAYMENT TYPES ===
payment
Credit card    354
Transfer       328
Cash           308
NaN             10
Name: count, dtype: int64

In [12]:
# Preview how Product Type looks when extracted from EntrDetails
# (the text before the "/" separator) -- this is applied for real later,
# in the Product Analysis notebook
product_types = products["EntrDetails"].str.split("/").str[0].str.strip()

print("=== PRODUCT TYPES ===")
print(product_types.value_counts())

=== PRODUCT TYPES ===
EntrDetails
Scooter          12
Naked bike        7
Sport             4
Cruiser           4
Adventure         4
Underbone         3
Dual-sport        3
Cafe racer        2
Commuter          2
Heritage          2
Retro             1
Sport touring     1
Classic           1
Scrambler         1
Standard          1
Touring           1
Street            1
Name: count, dtype: int64

In [13]:
# Create working copies so the original raw data is never modified directly
products_clean = products.copy()
sales_clean = sales.copy()

print("Clean copies created successfully.")

Clean copies created successfully.

In [14]:
# Identify which sales rows have a missing date, client_type, or payment value
missing_sales = sales_clean[
    sales_clean[["date", "client_type", "payment"]].isnull().any(axis=1)
]

missing_sales

          date client_type  ...     total      payment
7    8/14/2025         NaN  ...   8386000         Cash
65         NaN      Retail  ...   6510000  Credit card
84   6/15/2025         NaN  ...   2670000         Cash
119  6/28/2025   Wholesale  ...   2720000          NaN
186   8/9/2025         NaN  ...   1007200  Credit card
215   6/1/2025         NaN  ...   3493000         Cash
244  6/19/2025   Wholesale  ...   2772000          NaN
246   8/6/2025         NaN  ...   2232000     Transfer
311   7/3/2025   Wholesale  ...   1035000          NaN
318   7/8/2025   Wholesale  ...   1033500          NaN
370        NaN   Wholesale  ...   3802300  Credit card
398  8/25/2025   Wholesale  ...   3458000          NaN
467   8/8/2025   Wholesale  ...   2048000          NaN
492   7/2/2025      Retail  ...   5990000          NaN
524  8/29/2025         NaN  ...   2140300  Credit card
558  7/29/2025         NaN  ...   2184000         Cash
606   6/5/2025   Wholesale  ...   1132600          NaN
643  8/16/2025         NaN  ...   1484100     Transfer
660  8/19/2025         NaN  ...   9646000  Credit card
811  6/17/2025      Retail  ...  10080000          NaN
896  8/28/2025         NaN  ...   1984000  Credit card
977  6/14/2025   Wholesale  ...    534000          NaN

[22 rows x 7 columns]

In [15]:
# Fill missing categorical values with "Unknown" and convert the date
# column to a proper datetime type
sales_clean = sales.copy()

sales_clean["client_type"] = sales_clean["client_type"].fillna("Unknown")
sales_clean["payment"] = sales_clean["payment"].fillna("Unknown")

sales_clean["date"] = pd.to_datetime(
    sales_clean["date"],
    format="mixed",
    errors="coerce"
)

print("Date type:", sales_clean["date"].dtype)
print("Missing dates:", sales_clean["date"].isnull().sum())

Date type: datetime64[ns]
Missing dates: 6

In [16]:
# Identify which date values could not be parsed, so we know what will be dropped
test_dates = pd.to_datetime(
    sales["date"],
    format="mixed",
    errors="coerce"
)

failed_dates = sales[
    sales["date"].notna() & test_dates.isna()
]

print("Dates that failed conversion:")
print(failed_dates[["date"]])

Dates that failed conversion:
           date
328  2025/07/32
422  2025-08-00
665  08-40-2025
913  2025/07/32

In [17]:
# Drop the handful of rows with unparseable/invalid dates
sales_clean = sales_clean.dropna(subset=["date"]).copy()

print("Rows remaining:", len(sales_clean))
print("Missing dates:", sales_clean["date"].isnull().sum())

Rows remaining: 994
Missing dates: 0

In [18]:
# Recompute total from unitprice x quantity and flag rows where the
# recorded total disagrees with that calculation
sales_clean["calculated_total"] = (
    sales_clean["unitprice"] * sales_clean["quantity"]
)

mismatched_totals = sales_clean[
    sales_clean["total"] != sales_clean["calculated_total"]
]

print("Rows with incorrect totals:", len(mismatched_totals))
mismatched_totals.head()

Rows with incorrect totals: 20

          date client_type  ...      payment  calculated_total
3   2025-07-31      Retail  ...         Cash          43350000
23  2025-08-15      Retail  ...         Cash            826800
38  2025-08-01   Wholesale  ...  Credit card           3237300
99  2025-06-29   Wholesale  ...     Transfer           3738000
113 2025-06-08   Wholesale  ...     Transfer           1213500

[5 rows x 8 columns]

In [19]:
# Look up each sale's official unit price from the Product List and
# flag rows where the sale's unit price disagrees with it
price_lookup = products_clean.set_index("EntrName")["UnitPrice"]

sales_clean["product_list_price"] = sales_clean["product"].map(price_lookup)

price_mismatches = sales_clean[
    sales_clean["unitprice"] != sales_clean["product_list_price"]
]

print("Rows with unit price mismatch:", len(price_mismatches))

price_mismatches[
    ["product", "unitprice", "product_list_price", "quantity", "total"]
].head(20)

Rows with unit price mismatch: 34

                       product  unitprice  ...  quantity     total
3         Italjet Dragster 200     867000  ...        50  14450000
23        Keeway RKS 150 Sport     206700  ...         4    275600
38       Suzuki Raider R150 Fi     359700  ...         9   1079100
83            Yamaha Serow 25x     299000  ...        31   9269000
85       Suzuki Raider R150 Fx     119900  ...         2    239800
99                KTM Duke 200     534000  ...         7   1246000
113  Suzuki Burgman Street 125     242700  ...         5    404500
122         Bristol Veloce 500     984000  ...        12   3936000
125           Kawasaki KLX 23x     199000  ...        13   2587000
131        Moto Guzzi V7 Stone    2067000  ...         4   2756000
139          Yamaha Sniper 155     377700  ...         8   1007200
171      TVS Apache RTR 200 4V     387000  ...         9   1161000
185               CFMoto 300SR     495000  ...         7   1155000
195             Yamaha FZi 150     299700  ...        16   1598400
201                Bajaj CT12x      67900  ...        11    746900
223           Yamaha Serow 25x     299000  ...        32   9568000
380               Yamaha MT-15     534000  ...         5    890000
384            Suzuki GSX-S150     375000  ...        24   3000000
438               KTM 790 Dukx     599000  ...         3   1797000
524          Yamaha Sniper 15x     125900  ...        17   2140300

[20 rows x 5 columns]

In [20]:
# List sales product names that don't match any name in the Product
# List -- these are most likely typos
unmatched_products = sales_clean[
    sales_clean["product_list_price"].isna()
]["product"].value_counts()

print("=== SALES PRODUCTS NOT FOUND IN PRODUCT LIST ===")
print(unmatched_products)

=== SALES PRODUCTS NOT FOUND IN PRODUCT LIST ===
product
Yamaha Serow 25x          2
KTM 790 Dukx              2
Suzuki Raider R150 Fx     1
Kawasaki KLX 23x          1
Bajaj CT12x               1
Yamaha Sniper 15x         1
Bristol Bobber 65x        1
Yamaha MT-1x              1
Benelli 502x              1
TVS Apache RTR 200 4x     1
Motorstar Xplorer 250x    1
CFMoto 300Sx              1
Honda ADV 16x             1
Name: count, dtype: int64

In [21]:
# Use fuzzy string matching to suggest the correct product name for
# each unmatched entry
from difflib import get_close_matches

official_products = products_clean["EntrName"].tolist()

print("=== POSSIBLE PRODUCT NAME CORRECTIONS ===")

for name in unmatched_products.index:
    matches = get_close_matches(
        name,
        official_products,
        n=3,
        cutoff=0.5
    )
    print(name, "->", matches)

=== POSSIBLE PRODUCT NAME CORRECTIONS ===
Yamaha Serow 25x -> ['Yamaha Serow 250', 'Yamaha Sniper 155', 'Yamaha Aerox 155']
KTM 790 Dukx -> ['KTM 790 Duke', 'KTM Duke 200']
Suzuki Raider R150 Fx -> ['Suzuki Raider R150 Fi', 'Suzuki Avenis 125', 'Suzuki GSX-S150']
Kawasaki KLX 23x -> ['Kawasaki KLX 230', 'Kawasaki Z400', 'Kawasaki Ninja 400']
Bajaj CT12x -> ['Bajaj CT125']
Yamaha Sniper 15x -> ['Yamaha Sniper 155', 'Yamaha Serow 250', 'Yamaha Aerox 155']
Bristol Bobber 65x -> ['Bristol Bobber 650', 'Bristol Veloce 500']
Yamaha MT-1x -> ['Yamaha MT-15', 'Yamaha NMAX 155', 'Yamaha XSR155']
Benelli 502x -> ['Benelli 502C']
TVS Apache RTR 200 4x -> ['TVS Apache RTR 200 4V', 'Aprilia SR GT 200']
Motorstar Xplorer 250x -> ['Motorstar Xplorer 250R', 'Bristol Veloce 500']
CFMoto 300Sx -> ['CFMoto 300SR', 'CFMoto 300NK', 'CFMoto 650MT']
Honda ADV 16x -> ['Honda ADV 160', 'Honda Rebel 1100', 'Honda Click 125i']

In [22]:
# Apply the manually verified corrections for the typo'd product names
product_name_corrections = {
    "Yamaha Serow 25x": "Yamaha Serow 250",
    "KTM 790 Dukx": "KTM 790 Duke",
    "Suzuki Raider R150 Fx": "Suzuki Raider R150 Fi",
    "Kawasaki KLX 23x": "Kawasaki KLX 230",
    "Bajaj CT12x": "Bajaj CT125",
    "Yamaha Sniper 15x": "Yamaha Sniper 155",
    "Bristol Bobber 65x": "Bristol Bobber 650",
    "Yamaha MT-1x": "Yamaha MT-15",
    "Benelli 502x": "Benelli 502C",
    "TVS Apache RTR 200 4x": "TVS Apache RTR 200 4V",
    "Motorstar Xplorer 250x": "Motorstar Xplorer 250R",
    "CFMoto 300Sx": "CFMoto 300SR",
    "Honda ADV 16x": "Honda ADV 160"
}

sales_clean["product"] = sales_clean["product"].replace(product_name_corrections)

print("Product names corrected.")

Product names corrected.

In [23]:
# Re-check the price lookup now that the product names have been corrected
price_lookup = products_clean.set_index("EntrName")["UnitPrice"]

sales_clean["product_list_price"] = sales_clean["product"].map(price_lookup)

print(
    "Products still not found:",
    sales_clean["product_list_price"].isnull().sum()
)

Products still not found: 0

In [24]:
# Confirm which rows still have a unit price that disagrees with the Product List
price_mismatches = sales_clean[
    sales_clean["unitprice"] != sales_clean["product_list_price"]
]

print("Rows with unit price mismatch:", len(price_mismatches))

price_mismatches[
    ["product", "unitprice", "product_list_price", "quantity", "total"]
].head(20)

Rows with unit price mismatch: 20

                       product  unitprice  ...  quantity     total
3         Italjet Dragster 200     867000  ...        50  14450000
23        Keeway RKS 150 Sport     206700  ...         4    275600
38       Suzuki Raider R150 Fi     359700  ...         9   1079100
99                KTM Duke 200     534000  ...         7   1246000
113  Suzuki Burgman Street 125     242700  ...         5    404500
122         Bristol Veloce 500     984000  ...        12   3936000
131        Moto Guzzi V7 Stone    2067000  ...         4   2756000
139          Yamaha Sniper 155     377700  ...         8   1007200
171      TVS Apache RTR 200 4V     387000  ...         9   1161000
185               CFMoto 300SR     495000  ...         7   1155000
195             Yamaha FZi 150     299700  ...        16   1598400
380               Yamaha MT-15     534000  ...         5    890000
384            Suzuki GSX-S150     375000  ...        24   3000000
544               Zontes GK350     807000  ...        15   4035000
566               BMW G 310 GS     960000  ...        49  15680000
605               Yamaha MT-15     534000  ...        12   2136000
643              Honda ADV 160     494700  ...         9   1484100
647              Honda CBR500R    1167000  ...        47  18283000
648        Moto Guzzi V7 Stone    2067000  ...        14   9646000
667               Benelli 502C    1047000  ...         1    349000

[20 rows x 5 columns]

In [25]:
# Correct mismatched unit prices using the official Product List price
sales_clean.loc[
    sales_clean["unitprice"] != sales_clean["product_list_price"],
    "unitprice"
] = sales_clean["product_list_price"]

# Recalculate total based on corrected unit price
sales_clean["total"] = (
    sales_clean["unitprice"] * sales_clean["quantity"]
)

# Refresh calculated_total too -- previously this was left stale from before
# the price correction above, so for any row whose unitprice just changed,
# calculated_total no longer matched total/unitprice/quantity in the saved file.
sales_clean["calculated_total"] = (
    sales_clean["unitprice"] * sales_clean["quantity"]
)

print("Unit prices corrected using Product List.")
print(
    "Remaining unit price mismatches:",
    (sales_clean["unitprice"] != sales_clean["product_list_price"]).sum()
)

print(
    "Remaining incorrect totals:",
    (sales_clean["total"] !=
     sales_clean["unitprice"] * sales_clean["quantity"]).sum()
)

print(
    "Remaining stale calculated_total rows:",
    (sales_clean["calculated_total"] !=
     sales_clean["unitprice"] * sales_clean["quantity"]).sum()
)

Unit prices corrected using Product List.
Remaining unit price mismatches: 0
Remaining incorrect totals: 0
Remaining stale calculated_total rows: 0

In [26]:
# Run a final set of checks to confirm both datasets are fully cleaned
print("=== FINAL CLEANING VALIDATION ===")

print("\nProduct List:")
print("Rows:", len(products_clean))
print("Missing values:", products_clean.isnull().sum().sum())
print("Duplicate rows:", products_clean.duplicated().sum())
print("Duplicate Product IDs:", products_clean["EntrNo"].duplicated().sum())

print("\nSales Dataset:")
print("Rows:", len(sales_clean))
print("Missing values:", sales_clean.isnull().sum().sum())
print("Duplicate rows:", sales_clean.duplicated().sum())

print(
    "Products not matched:",
    sales_clean["product_list_price"].isnull().sum()
)

print(
    "Price mismatches:",
    (sales_clean["unitprice"] != sales_clean["product_list_price"]).sum()
)

print(
    "Incorrect totals:",
    (sales_clean["total"] !=
     sales_clean["unitprice"] * sales_clean["quantity"]).sum()
)

=== FINAL CLEANING VALIDATION ===

Product List:
Rows: 50
Missing values: 0
Duplicate rows: 0
Duplicate Product IDs: 0

Sales Dataset:
Rows: 994
Missing values: 0
Duplicate rows: 0
Products not matched: 0
Price mismatches: 0
Incorrect totals: 0

In [27]:
# Save the cleaned Product List and Sales datasets for use in the
# Product Analysis notebook
products_clean.to_csv(
    "MotorPH_Products_List_2025_Cleaned.csv",
    index=False
)

# product_list_price was only a lookup helper used to find/verify price
# mismatches -- it always equals unitprice once cleaning is done, so it
# does not need to ship in the final file.
sales_clean_to_save = sales_clean.drop(columns=["product_list_price"])

sales_clean_to_save.to_csv(
    "MotorPH_Sales_2025_Cleaned.csv",
    index=False
)

print("Cleaned files saved successfully!")
print("Product List: MotorPH_Products_List_2025_Cleaned.csv")
print("Sales Dataset: MotorPH_Sales_2025_Cleaned.csv")

Cleaned files saved successfully!
Product List: MotorPH_Products_List_2025_Cleaned.csv
Sales Dataset: MotorPH_Sales_2025_Cleaned.csv